export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  // home
  'home_card_navegacion': 'Lastest Activity',
  'home_card_navegacion_2': 'My Walls',
  'home_card_navegacion_3': 'My Short Stories',
  'home_card_navegacion_4': 'My Chatstories',
  'home_card_navegacion_5': 'Saved',

  'home_card_descubre': 'Improve your',
  'home_card_descubre_2': 'Walnov experience',
  'home_card_descubre_3': 'Find out how',

  'home_reciente_bienvenida': 'Right here you will find the latest content of the people that you follow!',
  'home_reciente_instrucciones': 'Start by following five of our community users at least',
  'home_reciente_instrucciones_2': 'Look for your friends!',

  'home_reciente_select_header': 'Sort by',
  'home_reciente_select_option_1': 'Relevant',
  'home_reciente_select_option_2': '+Liked',
  'home_reciente_select_option_3': '-Liked',
  'home_reciente_select_option_4': 'Followers',
  'home_reciente_select_option_5': 'Following',
  'home_reciente_select_option_6': '+Viewed',
  'home_reciente_select_option_7': '-Viewed',

  'home_reciente_suggested_users': 'Suggested users',
  'home_reciente_button_1': 'Continue',
  'home_reciente_placeholder': 'Write here your user name',
  'home_reciente_creacion': 'has written a new',
  'home_reciente_creacion_historia' : 'Story from the Wall',
  'home_reciente_participacion' : 'has taken part in the Wall',

  'home_buscador_mas': 'Show more',
  'home_buscador_nada': 'We have not found any result',
  'home_buscador_personas': 'People',
  'home_account_activation_button_text': 'Login',
  'home_account_activation_button_text_error': 'Get a new code',
  'home_account_activation_text': 'Welcome, your account has been activated, enjoy Walnov',

  // todo
  'all_relatos_cortos': 'Short stories',
  'all_relatos': 'Short stories',
  'all_relato_corto' : 'Short story',
  'all_siguiendo': 'Conected',
  'all_seguir': 'Conect',
  'all_participantes': 'Participants',
  'all_historias': 'Stories',
  'all_participar': 'Take part',
  'all_guardar': 'Save',
  'all_guardado': 'Saved',
  'all_guardando': 'Saving',
  'all_categorias': 'Categories',
  'all_categoria': 'Category',
  'all_todas': 'All',
  'all_texto': 'Text',
  'all_publicar': 'Post',
  'all_publicando': 'Posting',
  'all_nombre_usuario': 'Username',
  'all_continuaciones': 'Sequels',
  'all_opiniones': 'opinions',
  'all_visualizaciones': 'views',
  'all_like': 'Love',
  'all_compartir': 'Share',
  'all_reportar': 'Report',
  'all_donar': 'Donar',

  // categorias
  'accion': 'Action',
  'aventura': 'Adventure',
  'scifi': 'SCI-FI',
  'drama': 'Drama',
  'romance': 'Romance',
  'fanfic': 'FanFiction',
  'poesia': 'Poetry',
  'humor': 'Humor',
  'terror': 'Terror',
  'reflexion': 'Reflexion',

  // shared
  'shared_usuarios_tendencia': 'Top users',
  'shared_walls_relevantes': 'Relevant Walls',
  'shared_image_picker_changeimage' : 'Change',
  'shared_image_picker_changeimage_2' : 'Image',
  'shared_image_picker_selection' : 'Choose a picture',
  'shared_image_picker_upload' : 'Upload',
  'shared_image_picker_upload_2' : 'Upload an image',
  'shared_verify_user' : 'You must be a Verify User to upload a custom image',
  'shared_verify_user_upload' : 'Great, you are now a Verify User!',
  'shared_verify_user_browse' : 'Browse',
  'shared_verify_user_restrictions' : 'JPG Format - Minimum size',
  'shared_no_content_ver_chatstories': 'Oops! your ChatStories library is empty, What are you waiting for!',
  'shared_no_content_crear_chatstories': 'Oops! you have not created any ChatStories yet, What are you waiting for!',
  'shared_no_content_ver_chatstories_button_text': 'Check ChatStories',
  'shared_no_content_crear_chatstories_button_text': 'Create ChatStories',
  'shared_no_content_ver_relatos': 'Oops! your Short Stories library is empty, What are you waiting for!',
  'shared_no_content_mis_relatos': 'Oops! you have not created any Short Stories yet, What are you waiting for!',
  'shared_no_content_ver_relatos_button_text': 'Check Short Stories',
  'shared_no_content_crear_relatos_button_text': 'Create Short Stories',
  'shared_no_content_followers': 'Oops! no followers here!',

  // modal
  'modal_home': 'Great! Your own community has started',
  'modal_info': 'View users activity',
  'modal_compartir_enlace': 'Share link',
  'modal_compartir_redes': 'Share via',
  'modal_copy': 'Copy',
  'modal_copied': 'Copied',
  'modal_chatstory_posted': 'Chatstory posted successfully!',
  'modal_relato_posted': 'Short story posted successfully!',

  // alerts,warnings
  'alert_home': 'You must follow five users at least',
  'alert_borrador_no_encontrado': 'Draft not Found',
  'alert_home_chatstories': 'You have not written a Chatstory yet, ',
  'alert_home_chatstories2': 'Start right now!',

  'alert_crear_chatstory': 'Create one character at least',
  'alert_crear_chatstory_2': '15 characters maximum',
  'alert_crear_chatstory_3': 'Maximum of 18 characters',

  // ChatStories
  'alert_chatstory_existente': 'This Chatstory has already been posted',
  'alert_chatstory_requisitos': 'All Chatstories must have 5 chats to be posted',
  'alert_chatstory_insercion': 'An error has been detected while inserting a Chatstory',
  'alert_chatstory_borrador': 'Saved as draft',
  'alert_chatstory_borrador_updt': 'Your draft has been updated',
  'alert_chatstory_acabados' : 'You haven’t got more Chatstories!',
  'alert_chatstory_acabados_2': 'There’s no more Chatstories!',

  // Relatos
  'alert_relato_existente': 'This Short Story has already been posted',
  'alert_relato_requisitos': 'All Short Stories must have at least 140 characters to be posted',
  'alert_relato_insercion': 'An error has been detected while inserting a Short Story',
  'alert_relato_borrador': 'Saved as a draft',
  'alert_relato_borrador_updt': 'Your draft has been updated',
  'alert_relato_acabados' : 'You haven’t got more Short Stories!',
  'alert_relato_acabados_2': 'There’s no more Short Stories!',
  'alert_wrong_email': 'Write a valid email address',
  'alert_existent_email': 'This dedication already exists',
  'alert_existent_invitation': 'This invitation already exists',
  'alert_comment_length': 'Your comment must have at least 10 characters to be posted',

  'alert_relato_no_encontrado': 'ShortStory not found',

  'alert_popover_error': 'An error has occurred',

  'alert_bienvenido': 'Welcome',

  'alert_cuenta_registrada': 'Welcome, account registered check your email for activation link',
  'alert_email_ya_existe': 'Email already registered try another one',
  'alert_user_name_ya_existe': 'User name is associated with an existing account try another',
  'alert_sesion_terminada': 'Session finished',

  'alert_card_tags': 'Write a valid tag (Only letters/numbers)',
  'alert_card_tags_2': 'Maximum tag length: 15 characters',
  'alert_card_tags_3': 'This tag already exists',

  // chatstories
  'chatstorie_add_biblioteca': 'Add to my Library',
  'chatstorie_added_biblioteca': 'Added',

  'chatstories_biblioteca_buscador': 'My Chatstories’ Library',
  'chatstories_biblioteca_buscador_2': 'Well done!',
  'chatstories_biblioteca_buscador_3': 'Chatstory added to your library',
  'chatstories_biblioteca_buscador_4': 'Try to add more!',
  'chatstories_biblioteca_buscador_5': 'Add to your library your favourite Chatstories and enjoy them anytime',
  'chatstories_biblioteca_buscador_6': 'Go to my Library',

  'chatstories_creacion_header': 'Writing a Chatstory',
  'chatstories_creacion_step': 'Step',
  'chatstories_creacion_name': 'Chatstory’s title',
  'chatstories_creacion_name_placeholder': 'Write a title for your Chatstory',
  'chatstories_creacion_validate': 'Write a title',
  'chatstories_creacion_descripcion': 'Description',
  'chatstories_creacion_descripcion_placeholder': 'Tell everybody what is your Chatstory about',
  'chatstories_creacion_validate_2': 'Write a description',
  'chatstories_creacion_personajes': 'Characters maker',
  'chatstories_creacion_personajes_placeholder': 'Characters’ name',
  'chatstories_creacion_exclusivo': 'Exclusive Chatstory',
  'chatstories_creacion_footer': 'You are ready to write your Chatstory!',
  'chatstories_creacion_next': 'Next step',
  'chatstories_creacion_back' : 'Back to step one',
  'chatstories_creacion_personaje' : 'Character',
  'chatstories_creacion_personaje_name' : 'Characters’ name',
  'chatstories_creacion_add_image' : 'Add a picture',
  'chatstories_creacion_add_message' : 'Add message',
  'chatstories_creacion_save_changes' : 'Save changes',
  'chatstories_creacion_delete_message' : 'Delete message',
  'chatstories_creacion_publica_message' : 'Everythig ok? Post your Chatstory now!',
  'chatstories_creacion_guardar_borrador' : 'Save as draft',

  'chatstories_mi_biblioteca': 'My library',
  'chatstories_mi_biblioteca_message': 'No Chatstories added to this category yet',
  'chatstories_mi_biblioteca_message_2': 'Let’s do it right now!',

  'chatstories_ver_footer': 'Press the spacebar or click here for more messages',

  'mis_chatstories_message': 'You haven’t written any Chatstory yet,',
  'mis_chatstories_message_2': 'what are you waiting for?',
  'mis_chatstories_fecha': 'Last update',

  'chatstories_relevantes': 'Relevant Chatstories',
  'chatstories_relevantes_leer': 'Read',

  'chatstories_card_info': 'Chatstory info',
  'chatstories_card_info_personajes': 'character(s)',

  // card-informativo
  'card_info_entendido': 'Got it',
  'card_info_instr': 'Start by choosing a title and a category.',
  'card_info_title': 'You are writing a',
  'card_info_instr_wall': 'Choose a picture and write the beginning of your story.',
  'card_info_instr_chat': 'Choose a picture and bring your characters to life.',
  'card_info_instr_chat_2': 'If they are ready let’s write the conversation. Make it interesting!',
  'card_info_instr_relato': 'Choose a picture and write your Short story. Let’s go!',
  'card_info_instr_2': 'Don’t forget to tell your friends and share your content on the social media!',

  // forms
  'forms_nombre': 'Name',
  'forms_nombre_placeholder': 'Write your name here',
  'forms_apellidos': 'Last name',
  'forms_idioma': 'Language',
  'forms_edad': 'Age',
  'forms_pais': 'Country',
  'forms_verificar': 'Verify me',
  'forms_cancelar': 'Cancel',
  'forms_hecho': 'Done',
  'forms_username': 'Username',
  'forms_fecha_nacimiento': 'Birthday',
  'forms_sexo': 'Gender',
  'forms_mujer': 'Female',
  'forms_hombre': 'Male',
  'forms_telefono' : 'Phone number',
  'forms_idiomas_placeholder': 'Languages',
  'forms_intereses': 'Interests',
  'forms_guardar_cambios': 'Save changes',
  'forms_pago': 'Payment form',
  'forms_primer_apellido': 'First surname',
  'forms_primer_apellido_placeholder': '1st surname',
  'forms_segundo_apellido': 'Second surname',
  'forms_segundo_apellido_placeholder': '2nd surname',
  'forms_recibo': 'for the receipt',
  'forms_introduce': 'Write here your',
  'forms_tarjeta': 'Credit card number',
  'forms_pagar_con': 'Pay by',
  'forms_fecha_cadudicad': 'Expiry date',
  'forms_mes': 'Month',
  'forms_año': 'Year',
  'forms_codigo_seguridad': 'Security code',
  'forms_propietario_tarjeta': 'Card owner’s name',
  'forms_propietario_tarjeta_placeholder': 'Name Surname Surname',
  'forms_confirmacion': 'I have read  Walnov’s conditions and policy and I accept them.',
  'forms_confirmar': 'Confirm',

  // idiomas
  'español': 'Spanish',
  'english': 'English',
  'frances': 'French',
  'portugues': 'Portuguese',
  'chino': 'Chinese',
  'japones': 'Japanese',
  'italiano': 'Italian',
  'ruso': 'Russian',

  // Intereses
  'deportes': 'Sport',
  'cultura': 'Culture',
  'historia': 'History',
  'arte': 'Art',
  'musica': 'Music',
  'viajar': 'Travel',
  'fantasia': 'Fantasy',
  'misterio': 'Mistery',

  // user-profile
  'user_profile_conectar': 'Connect',
  'user_profile_message': 'Send message',
  'user_profile_seguidores': 'Followers',
  'user_profile_todos': 'See all',
  'user_profile_apoyar': 'Support',
  'user_profile_apoyar_message': 'to write more and better',
  'user_profile_suscribir': 'Suscribe',
  'user_profile_suscrito': 'Suscribed',
  'user_profile_desuscribir': 'Unsuscribe',

  // continuaciones
  'card_continuacion': 'Sequel',

  // card-tags
  'add_tags': 'Add tags to your',

  // Relatos
  'relatos_creacion': 'Short story Creation',
  'relatos_dedicatoria': 'Do you want to dedicate your Short story?',
  'relatos_dedicatoria_placeholder': 'name@mail.com; @username…',
  'relatos_mensaje': 'Invite your friends',
  'relatos_mensaje_placeholder': '@Friends’name',
  'relatos_titulo' : 'Short story’s title',
  'relatos_restriccion': 'Write a 30-chatacters-maximum title',
  'relatos_restriccion_2': 'Text from 140 to 3000 characters',
  'relatos_restriccion_3': 'Your Short story’s length must be between 140 and 3000 characters',
  'relatos_vista_previa': 'Preview',
  'relatos_card_info': 'Short story info',
  'relatos_añadir': 'Add to my lists',
  'relatos_eliminar': 'Remove from my lists',
  'relatos_relevantes': 'Relevant Short stories',


  // popover
  'popover_unirse': 'Join us to post your content',
  'popover_registro': 'Sign in with:',
  'popover_contraseña': 'Password',
  'popover_error_mail': 'Write a valid mail',
  'popover_error_contraseña': 'Write a valid password (8 characters min)',
  'popover_error_nombre': 'Write a valid username',
  'popover_error_olvidada': 'I have forgot my password',
  'popover_request_account_activation_link': 'Activation link lost?',
  'popover_ya_registrado': 'I have an account, log in',
  'popover_no_registrado': 'I don’t have an account, sign in',
  'popover_unirse_2': 'Join',
  'popover_entrar': 'Log in',
  'popover_activacion': 'Send',

  // profile-popover
  'profile_popover_cuenta': 'Account',
  'profile_popover_salir': 'Log out',
  'profile_popover_nivel': 'Go up a level!',

  // nav
  'nav_crear': 'Write',
  'nav_crear_un': 'Write a',
  'nav_como_funciona': 'How it works',

  // comentarios
  'dejar_comentario': 'Let your comment',
  'dejar_comentario_placeholder': '750 characters maximum',

  // user-account
  'user_cuenta': 'Account',
  'user_profile': 'Profile details',
  'user_preferencias': 'Preferences',
  'user_premium': 'My Premium account',
  'user_descripcion': 'Description',
  'user_details': 'My details',
  'user_preferencias_mensajes': 'Messages',
  'user_preferencias_notificaciones': 'Notifications',

  // contacto
  'contacto_contactar': 'Contact with us',
  'contacto_nombre_placeholder': 'Write your name here',
  'contacto_email_placeholder': 'Write your email here',
  'contacto_asunto': 'Subject',
  'contacto_asunto_placeholder': 'Write a subject',
  'contacto_mensaje': 'Message',
  'contacto_mensaje_placeholder': 'Write your message here',
  'contacto_enviar': 'Send',
  'contacto_mapa': 'You can find us here:',
  'contacto_calle': 'Pedro Duque’s street, Valencia, Spain',
  'contacto_edificio': '9B building, office number 19',

  // pricing-partner
  'partner_titulo': 'Become a Walnov’s Partner',
  'partner_oferta': 'Earn money by doing the most you like, Writing!',
  'partner_pregunta': 'What do we offer?',
  'partner_suscripcion': 'Suscribe now for 4,99€',
  'partner_suscripcion_2': 'Walnov users can suscribe to your content and be the first ones in get it',
  'partner_apoyo': 'Your fans can make donations to you and you won’t stop writing!',
  'partner_donacion': 'Make a _ _ _€ donation',
  'partner_iconos': 'Special icons for your fans. You can design an icon for your fans and it will appear on their profile',
  'partner_mas': 'What’s better, you can earn money for every post you make!',
  'partner_mas_2': 'To be partner you need to be an active user who writes high-quality-content for a lot of followers. ' +
  'Do you think you fit in? Start right now!',
  'partner_solicitud': 'Send my request',

  // pricing-premium
  'premium_pasarse': 'Go Premium',
  'premium_texto': 'Support the biggest Colaborative-Writing-Community and make it grow to generate amazing content',
  'premium_mensual': 'Monthly subscription',
  'premium_mensual_precio': '5.99€/month',
  'premium_iva': 'V.A.T included',
  'premium_cancelacion': 'You can cancel your subscription whenever you want',
  'premium_contenido': 'Read chatstories from PC without limit',
  'premium_contenido_2': 'Read chatstories from mobile phone without limit',
  'premium_contenido_3': 'Free-ads web/app browsing',
  'premium_contenido_4': 'Free books and ebooks',
  'premium_contenido_5': 'Exclusive chatstories/walls/short stories',
  'premium_contenido_6': 'Download stories on offline mode from the app.',
  'premium_contenido_7': 'Prior access to users content.',
  'premium_contenido_8': '50% off subscription to a user per month.',
  'premium_lo_quiero': 'I want it!',
  'premium_anual': 'Anual subscription',
  'premium_anual_precio': '3.49€/month',
  'premium_contenido_9': '30% off subscription',
  'premium_diario': 'Daily payment',
  'premium_diario_precio': '0.99€/day',
  'premium_diario_acceso': 'A full premium access day',
  'premium_prueba_texto': 'Try the 7-free-days period and you won’t regret!',
  'premium_prueba_solicitud': 'Try it!',
  'premium_confirmar_plan' : 'Confirm your subscription',
  'premium_prueba_confirmacion': 'We need some extra details before you get the 7-free-days period',
  'premium_prueba_final': 'When it finishes, you’ll pay XX.XX€/month-year.',

  // selector_idioma
  'selector_titulo': 'Language',

  // landingMobiled
  'landing_mobile_mensaje': 'Leave your mark',
  'landing_mobile_descarga': 'Get the app on your phone',

  // 404
  'pagina_no_encontrada': 'Page not found',
  'pagina_no_encontrada_mensaje': 'Ups! It seems our writers have lost their papers and we can’t find what you’re looking for...',
  'pagina_no_encontrada_mensaje_2': 'You can keep browsing if you want:',

  // Notificaciones
  'notificaciones_ver_todas': 'See all notifications',
};
